export type Account = {
	id: number;
	name: string;
	iban: string;
	brandInitials: string;
	brandColor: string;
	status: "ok" | "warn" | "err";
	statusLabel: string;
	expiresInDays: number;
	lastSync: Date;
};

export type SyncRun = {
	id: number;
	at: Date;
	trigger: "cron" | "manual";
	status: "ok" | "warn" | "err";
	statusLabel: string;
	imported: number;
	skipped: number;
	message: string;
	durationMs: number;
};

const now = new Date("2026-04-30T00:00:00Z");
const ago = (h: number) => new Date(now.getTime() - h * 3_600_000);
const future = (h: number) => new Date(now.getTime() + h * 3_600_000);

export const accounts: Account[] = [
	{
		id: 1,
		name: "Millennium BCP — Checking",
		iban: "PT50 0010 0001 2345 6789 1510 2",
		brandInitials: "BCP",
		brandColor: "#e30613",
		status: "ok",
		statusLabel: "OK",
		expiresInDays: 162,
		lastSync: ago(2),
	},
	{
		id: 2,
		name: "N26 — Main Account",
		iban: "DE89 3704 0044 0532 0130 00",
		brandInitials: "N26",
		brandColor: "#1a1a1a",
		status: "warn",
		statusLabel: "WARN",
		expiresInDays: 5,
		lastSync: ago(2),
	},
	{
		id: 3,
		name: "Revolut — EUR",
		iban: "LT12 3250 0718 9900 3578",
		brandInitials: "REV",
		brandColor: "#0075eb",
		status: "ok",
		statusLabel: "OK",
		expiresInDays: 89,
		lastSync: ago(2),
	},
];

export const syncRuns: SyncRun[] = [
	{
		id: 30,
		at: ago(2),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 3,
		skipped: 0,
		message: "3 new txns across 3 accounts",
		durationMs: 842,
	},
	{
		id: 29,
		at: ago(8),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 0,
		skipped: 0,
		message: "Nothing new",
		durationMs: 611,
	},
	{
		id: 28,
		at: ago(14),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 12,
		skipped: 2,
		message: "12 txns, 2 pending skipped",
		durationMs: 903,
	},
	{
		id: 27,
		at: ago(20),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 7,
		skipped: 0,
		message: "7 new txns",
		durationMs: 774,
	},
	{
		id: 26,
		at: ago(26),
		trigger: "manual",
		status: "warn",
		statusLabel: "WARN",
		imported: 4,
		skipped: 0,
		message: "N26 session expiring in 5d",
		durationMs: 991,
	},
	{
		id: 25,
		at: ago(32),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 1,
		skipped: 0,
		message: "1 new txn",
		durationMs: 558,
	},
	{
		id: 24,
		at: ago(38),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 0,
		skipped: 0,
		message: "Nothing new",
		durationMs: 594,
	},
	{
		id: 23,
		at: ago(44),
		trigger: "cron",
		status: "err",
		statusLabel: "ERR",
		imported: 0,
		skipped: 0,
		message: "GoCardless 429 — rate limited",
		durationMs: 1203,
	},
	{
		id: 22,
		at: ago(50),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 9,
		skipped: 1,
		message: "9 txns, 1 duplicate skipped",
		durationMs: 687,
	},
	{
		id: 21,
		at: ago(56),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 5,
		skipped: 0,
		message: "5 new txns",
		durationMs: 731,
	},
	{
		id: 20,
		at: ago(62),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 0,
		skipped: 0,
		message: "Nothing new",
		durationMs: 579,
	},
	{
		id: 19,
		at: ago(68),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 18,
		skipped: 0,
		message: "18 new txns",
		durationMs: 1042,
	},
	{
		id: 18,
		at: ago(74),
		trigger: "manual",
		status: "ok",
		statusLabel: "OK",
		imported: 2,
		skipped: 0,
		message: "2 new txns — manual trigger",
		durationMs: 823,
	},
	{
		id: 17,
		at: ago(80),
		trigger: "cron",
		status: "warn",
		statusLabel: "WARN",
		imported: 6,
		skipped: 3,
		message: "ING consent expires in 12d",
		durationMs: 876,
	},
	{
		id: 16,
		at: ago(86),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 0,
		skipped: 0,
		message: "Nothing new",
		durationMs: 601,
	},
	{
		id: 15,
		at: ago(92),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 11,
		skipped: 1,
		message: "11 txns, 1 duplicate skipped",
		durationMs: 789,
	},
	{
		id: 14,
		at: ago(98),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 4,
		skipped: 0,
		message: "4 new txns",
		durationMs: 664,
	},
	{
		id: 13,
		at: ago(104),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 0,
		skipped: 0,
		message: "Nothing new",
		durationMs: 587,
	},
	{
		id: 12,
		at: ago(110),
		trigger: "cron",
		status: "err",
		statusLabel: "ERR",
		imported: 0,
		skipped: 0,
		message: "Actual Budget unreachable — timeout",
		durationMs: 5001,
	},
	{
		id: 11,
		at: ago(116),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 8,
		skipped: 0,
		message: "8 new txns",
		durationMs: 712,
	},
	{
		id: 10,
		at: ago(122),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 3,
		skipped: 0,
		message: "3 new txns",
		durationMs: 698,
	},
	{
		id: 9,
		at: ago(128),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 0,
		skipped: 0,
		message: "Nothing new",
		durationMs: 563,
	},
	{
		id: 8,
		at: ago(134),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 21,
		skipped: 0,
		message: "21 new txns",
		durationMs: 1134,
	},
	{
		id: 7,
		at: ago(140),
		trigger: "manual",
		status: "ok",
		statusLabel: "OK",
		imported: 7,
		skipped: 2,
		message: "7 txns, 2 pending skipped",
		durationMs: 841,
	},
	{
		id: 6,
		at: ago(146),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 0,
		skipped: 0,
		message: "Nothing new",
		durationMs: 571,
	},
	{
		id: 5,
		at: ago(152),
		trigger: "cron",
		status: "warn",
		statusLabel: "WARN",
		imported: 5,
		skipped: 0,
		message: "Revolut rate limit warning (80%)",
		durationMs: 934,
	},
	{
		id: 4,
		at: ago(158),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 14,
		skipped: 0,
		message: "14 new txns",
		durationMs: 977,
	},
	{
		id: 3,
		at: ago(164),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 2,
		skipped: 1,
		message: "2 txns, 1 duplicate skipped",
		durationMs: 645,
	},
	{
		id: 2,
		at: ago(170),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 0,
		skipped: 0,
		message: "Nothing new",
		durationMs: 588,
	},
	{
		id: 1,
		at: ago(176),
		trigger: "cron",
		status: "ok",
		statusLabel: "OK",
		imported: 9,
		skipped: 0,
		message: "9 new txns — first run",
		durationMs: 1021,
	},
];

export const lastSync = ago(2);
export const nextSync = future(4);
